#! /bin/sh

bspc config border_width 1
bspc config window_gap 4

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

bspc monitor DVI-0 -d I II III IV V
bspc monitor DVI-1 -d VI VII VIII IX X
